name: Continuous Integration

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        node-version: '20'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set pythonpath
      run: |
        WORKSPACE=$(pwd)
        
        echo "PYTHONPATH=$WORKSPACE:$PYTHONPATH" >> "$GITHUB_ENV"

    - name: Run pytest
      run: |
        pytest

    - name: Run flake8
      run: |
        flake8 --exclude=sanitycheck.py --ignore=E501
